# @package _group_

# crop size:
#  - false for not cropping;
#  - int n for cropping square [n. n];
#  - [h, w] for cropping specific size/
crop: 256


# downsample factor.
#  - value > 1 for downsample;
#  - 0.x for upsample;
#  - [h, w] for specific size;
#  - false for not resizing.
downsample: [ 1920, 1080 ]

h-flip: true
v-flip: true

lightness_adjust: true
contrast_adjust: true