# @package _group_

# crop size:
#  - false for not cropping;
#  - int n for cropping square [n. n];
#  - [h, w] for cropping specific size/
crop: 512


# downsample factor.
#  - value > 1 for downsample;
#  - 0.x for upsample;
#  - [h, w] for specific size;
#  - false for not resizing.
downsample: false

h-flip: true
v-flip: true

lightness_adjust: false
contrast_adjust: false