expname: debug
num_epoch: 1000
gpu: 3
valid_every: 10
log_every: 1
save_model_every: 1
checkpoint_filepath: false # false for no checkpoint

GT_dirpath: "/data1/why/deep_local_parametric_filters/data_eval/output"
input_dirpath: "/data1/why/deep_local_parametric_filters/data_eval/input"

transforms:
  crop: 32     # crop size, false for not cropping.  
  resize: 10   # downsample factor. 0.x for upsample; false for not resizing.
  horizon_flip: true
  vertical_flip: true