expname: debug
num_epoch: 1000
gpu: 0
valid_every: 10
save_model_every: 1
checkpoint_filepath: false # false for no checkpoint

GT_dirpath: "/data1/why/deep_local_parametric_filters/data_eval/output"
input_dirpath: "/data1/why/deep_local_parametric_filters/data_eval/input"

transforms:
  crop: 512     # crop size, false for not cropping.  
  resize: 1.5   # downsample factor. 0.x for upsample; false for not resizing.
  horizon_flip: true
  vertical_flip: true