expname: full_data-resize
num_epoch: 1000
gpu: 2
valid_every: 10
log_every: 100
save_model_every: 1
checkpoint_filepath: false # false for no checkpoint

GT_dirpath: /data1/why/full_data/full_data/output
input_dirpath: /data1/why/full_data/full_data/input

transforms:
  crop: false # crop size, false for not cropping.
  resize: 3.5 # downsample factor. 0.x for upsample; false for not resizing.
  horizon_flip: true
  vertical_flip: true
