expname: indoor-resize
num_epoch: 1000
gpu: 1
valid_every: 10
log_every: 100
save_model_every: 1
checkpoint_filepath: false # false for no checkpoint

GT_dirpath: /home/haoyuanwang/deepLPF/indoor/gt_indoor
input_dirpath: /home/haoyuanwang/deepLPF/indoor/input_indoor

transforms:
  crop: false # crop size, false for not cropping.
  resize: 1.5 # downsample factor. 0.x for upsample; false for not resizing.
  horizon_flip: true
  vertical_flip: true
