"""
Put read-only global variables here.
! DO NOT EDIT THIS FILE UNLESS YOU KNOW WHAT YOU ARE DOING
"""
from rich.console import Console

console = Console()
import sys

sys.path.append('./')
from torch.cuda import is_available as cuda_available

CUDA_AVAILABLE = cuda_available()

########################################
### The following part CAN be edited ###
# Constants
EVAL_RESULT_PATH = '../eval_results/'
LOG_FILENAME = 'run.log'
LOG_TIME_FORMAT = '%Y-%m-%d_%H:%M:%S'
INPUT = 'input'
OUTPUT = 'output'
STRING_FALSE = 'False'

# fields in data.py (result of dataset[i])s
INPUT_IMG = 'input_img'
OUTPUT_IMG = 'output_img'
NAME = 'name'

# config.yml
CHECKPOINT_PATH = 'checkpoint_path'
LOG_DIRPATH = 'log_dirpath'
IMG_DIRPATH = 'img_dirpath'
# SAVE_MODEL_EVERY = 'save_model_every'
DATALOADER_NUM_WORKER = 'dataloader_num_worker'
INPUT_DIRPATH = 'input_dirpath'
VALID_EVERY = 'valid_every'
GT_DIRPATH = 'GT_dirpath'
AUGMENTATION = 'aug'
NUM_EPOCH = 'num_epoch'
LOG_EVERY = 'log_every'
EXPNAME = 'name'
LOSS = 'loss'
DATA = 'ds'
GPU = 'gpu'
RUNTIME = 'runtime'
MODELNAME = 'modelname'

# config.loss
LTV_LOSS = 'ltv'
COS_LOSS = 'cos'
SSIM_LOSS = 'ssimLoss'
L1_LOSS = 'L1Loss'

# config.aug
VERTICAL_FLIP = 'v-flip'
HORIZON_FLIP = 'h-flip'
RESIZE = 'resize'
CROP = 'crop'

# config.runtime.modelname
DEEP_LPF = 'deeplpf'

# config.runtime.deeplpf.*
PREDICT_ILLUMINATION = 'predict_illumination'
FILTERS = 'filters'
USE_GRADUATED_FILTER = 'g'
USE_ELLIPTICAL_FILTER = 'e'

# running mode
TRAIN = 'train'
TEST = 'test'
EVAL = 'eval'

# file / dir name
IMAGES = 'images'

# models name
SUPPORTED_MODELS = [
    DEEP_LPF
]

# required arguments in any condition:
GENERAL_NECESSARY_ARGUMENTS = [
    EXPNAME,
    RUNTIME,
    GPU,
    DATA,
]

# extra required arguments for all models when training:
TRAIN_NECESSARY_ARGUMENTS = [
    NUM_EPOCH,
    VALID_EVERY,
    LOG_EVERY,
    # SAVE_MODEL_EVERY,
    AUGMENTATION,
]

# extra required arguments for all models when testing/evaluating:
TEST_NECESSARY_ARGUMENTS = [
    CHECKPOINT_PATH,
]

# extra required arguments for each model:
RUNTIME_NECESSARY_ARGUMENTS = {
    DEEP_LPF: [
    ],
}

#############################################
#### The following part CAN NOT be edited ###
ARGUMENTS_MISSING_ERRS = {}
for ls in [GENERAL_NECESSARY_ARGUMENTS, TRAIN_NECESSARY_ARGUMENTS, TEST_NECESSARY_ARGUMENTS]:
    for x in ls:
        ARGUMENTS_MISSING_ERRS[x] = f'ERR: Config missing argument: {x}'
