"""
Put read-only global variables here.
! DO NOT EDIT THIS FILE UNLESS YOU KNOW WHAT YOU ARE DOING
"""
from rich.console import Console

console = Console()
from model.DeepLPF import DeepLPFNet
from torch.cuda import is_available as cuda_available

CUDA_AVAILABLE = cuda_available()

# Models-mapping
MODEL_ZOO = {
    'deeplpf': DeepLPFNet,
    '3dlut': None
}

# Path
EVAL_RESULT_PATH = '../eval_results/'

# config.yml
PREDICT_ILLUMINATION = 'predict_illumination'
CHECKPOINT_FILEPATH = 'model_path'
SAVE_MODEL_EVERY = 'save_model_every'
TIME_FORMAT = '%Y-%m-%d_%H:%M:%S'
INPUT_DIRPATH = 'input_dirpath'
VALID_EVERY = 'valid_every'
GT_DIRPATH = 'GT_dirpath'
TRANSFORMS = 'aug'
NUM_EPOCH = 'num_epoch'
LOG_EVERY = 'log_every'
EXPNAME = 'name'
LOSSES = 'loss'
DATA = 'data'
GPU = 'gpu'
FILTERS = 'filters'
USE_GRADUATED_FILTER = 'use_graduated_filter'
USE_ELLIPTICAL_FILTER = 'use_elliptical_filter'

# config::losses
# LOCAL_SMOOTHNESS_LOSS = 'ltvLoss'
LTV_LOSS = 'ltv'
COS_LOSS = 'cos'
SSIM_LOSS = 'ssimLoss'
L1_LOSS = 'L1Loss'
STRING_FALSE = 'False'

# config::transforms
VERTICAL_FLIP = 'v-flip'
HORIZON_FLIP = 'h-flip'
RESIZE = 'resize'
CROP = 'crop'

# model.py
INPUT = 'input'
OUTPUT = 'output'

# data.py
INPUT_IMG = 'input_img'
OUTPUT_IMG = 'output_img'
NAME = 'name'

# config mode
TRAIN = 'train'
TEST = 'test'

# file / dir name
IMAGES = 'images'
MODELNAME = 'deep_lpf'

trainNecessaryFields = [
    EXPNAME,
    NUM_EPOCH,
    GPU,
    VALID_EVERY,
    LOG_EVERY,
    SAVE_MODEL_EVERY,
    CHECKPOINT_FILEPATH,
    DATA,
    TRANSFORMS,
    PREDICT_ILLUMINATION,
    LOSSES,
    FILTERS
]

testNecessaryFields = [
    EXPNAME,
    GPU,
    CHECKPOINT_FILEPATH,
    DATA,
    TRANSFORMS,
    PREDICT_ILLUMINATION,
    FILTERS
]
